
import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import { AppProviders } from "@/components/providers/AppProviders";
import { Toaster } from "@/components/ui/sonner";
import { useDispatch } from "react-redux";
import { startWebSocket } from "@/lib/startWebSocket";
import { useAppDispatch } from "@/store/hook";
import { WebSocketProvider } from "@/components/providers/WebSocketProvider";

const inter = Inter({ subsets: ["latin"] });
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={inter.className}
      >
        <AppProviders>
        <WebSocketProvider/>
          {children}
        </AppProviders>
      </body>
      <Toaster richColors/>
    </html>
  );
}
